///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Desktop_Automation_Gotis
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Desktop_Automation_GotisRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("d1c2428f-4f9f-4b49-9cc3-e9d803733818")]
    public partial class Desktop_Automation_GotisRepository : RepoGenBaseFolder
    {
        static Desktop_Automation_GotisRepository instance = new Desktop_Automation_GotisRepository();
        Desktop_Automation_GotisRepositoryFolders.Book11ExcelAppFolder _book11excel;

        /// <summary>
        /// Gets the singleton class instance representing the Desktop_Automation_GotisRepository element repository.
        /// </summary>
        [RepositoryFolder("d1c2428f-4f9f-4b49-9cc3-e9d803733818")]
        public static Desktop_Automation_GotisRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Desktop_Automation_GotisRepository() 
            : base("Desktop_Automation_GotisRepository", "/", null, 0, false, "d1c2428f-4f9f-4b49-9cc3-e9d803733818", ".\\RepositoryImages\\Desktop_Automation_GotisRepositoryd1c2428f.rximgres")
        {
            _book11excel = new Desktop_Automation_GotisRepositoryFolders.Book11ExcelAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("d1c2428f-4f9f-4b49-9cc3-e9d803733818")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Book11Excel folder.
        /// </summary>
        [RepositoryFolder("0adf07bc-1a4b-4842-ac4b-4e057a0517a5")]
        public virtual Desktop_Automation_GotisRepositoryFolders.Book11ExcelAppFolder Book11Excel
        {
            get { return _book11excel; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Desktop_Automation_GotisRepositoryFolders
    {
        /// <summary>
        /// The Book11ExcelAppFolder folder.
        /// </summary>
        [RepositoryFolder("0adf07bc-1a4b-4842-ac4b-4e057a0517a5")]
        public partial class Book11ExcelAppFolder : RepoGenBaseFolder
        {
            Desktop_Automation_GotisRepositoryFolders.Sheet1Folder _sheet1;
            RepoItemInfo _blankworkbookInfo;
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _filesaveInfo;
            RepoItemInfo _desktopautomationtestInfo;
            RepoItemInfo _buttonsaveInfo;
            RepoItemInfo _celleInfo;
            RepoItemInfo _cell4Info;
            RepoItemInfo _insertInfo;
            RepoItemInfo _cellfInfo;
            RepoItemInfo _deleteInfo;
            RepoItemInfo _statusbarInfo;
            RepoItemInfo _closeInfo;
            RepoItemInfo _saveInfo;
            RepoItemInfo _cancelInfo;
            RepoItemInfo _cell7Info;

            /// <summary>
            /// Creates a new Book11Excel  folder.
            /// </summary>
            public Book11ExcelAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Book11Excel", "/form[@processname='EXCEL']", parentFolder, 60000, null, true, "0adf07bc-1a4b-4842-ac4b-4e057a0517a5", "")
            {
                _sheet1 = new Desktop_Automation_GotisRepositoryFolders.Sheet1Folder(this);
                _blankworkbookInfo = new RepoItemInfo(this, "BlankWorkbook", ".//container[@automationid='BackstageView']/?/?/container[@automationid='PlaceTabHomeContent']/container[@automationid='HomePageSlabCreateNew']/?/?/listitem[@name='Blank workbook']", ".//listitem[@name='Blank workbook']", 30000, null, "bd80e14e-40f5-46f5-9522-83bae726afe9");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "button[@accessiblename='OK']", "button[@accessiblename='OK']", 30000, null, "4e5af33e-e3f1-4949-9053-462492a94660");
                _filesaveInfo = new RepoItemInfo(this, "FileSave", "element[3]//container[@name='Ribbon']/toolbar[@name='Quick Access Toolbar']/button[@automationid='FileSave']", ".//button[@automationid='FileSave']", 30000, null, "da61aaed-aa63-40b4-ad20-30e6442f0a2d");
                _desktopautomationtestInfo = new RepoItemInfo(this, "DesktopAutomationTest", ".//container[@automationid='BackstageView']//list[@classname='NetUICoreListView']/container[@name='Today']/listitem[@name='Desktop Automation Test']", ".//listitem[@name='Desktop Automation Test']", 30000, null, "54f041f4-2a87-4bd8-8585-3e7d4e95725b");
                _buttonsaveInfo = new RepoItemInfo(this, "ButtonSave", "button[@text='&Save']", "button[@text='&Save']", 30000, null, "6eea1926-b203-4e78-940a-fa9c5bced349");
                _celleInfo = new RepoItemInfo(this, "CellE", ".//container[@automationid='Book11']/?/?/table[@automationid='Grid']/cell[@name='E']", ".//cell[@name='E']", 30000, null, "d6ef9780-c0fa-4604-805e-0cbcdd4d30c4");
                _cell4Info = new RepoItemInfo(this, "Cell4", ".//container[@automationid='desktop automation.xlsx']/?/?/table[@automationid='Grid']/cell[@name='4']", ".//cell[@name='4']", 30000, null, "8296625c-faae-4f8c-9fb7-1394afece428");
                _insertInfo = new RepoItemInfo(this, "Insert", "?/?/container[@classname='NetUIPanViewer']/container[2]/menuitem[@name='Insert']", ".//menuitem[@name='Insert']", 30000, null, "7e697a46-2f23-4edb-b004-9c978ace0347");
                _cellfInfo = new RepoItemInfo(this, "CellF", ".//container[@automationid='desktop automation.xlsx']/?/?/table[@automationid='Grid']/cell[@name='F']", ".//cell[@name='F']", 30000, null, "269ffb61-d4a8-487a-b201-88120e341fe6");
                _deleteInfo = new RepoItemInfo(this, "Delete", "?/?/container[@classname='NetUIPanViewer']/container[2]/menuitem[@name='Delete']", ".//menuitem[@name='Delete']", 30000, null, "fd815826-7012-4b8f-aded-cdcc7c9632a9");
                _statusbarInfo = new RepoItemInfo(this, "StatusBar", "element[@instance='1']/container[@caption='Status Bar']//statusbar[@name='Status Bar']", ".//statusbar[@name='Status Bar']", 20000, null, "b9a6dab5-636c-4f5b-a034-809a31680395");
                _closeInfo = new RepoItemInfo(this, "Close", "element[3]/container[@caption='Ribbon']//container[@name='Ribbon']/button[@name='Close']", ".//button[@name='Close']", 20000, null, "a87772c0-540f-4ef0-afbe-ae54fb2fc0af");
                _saveInfo = new RepoItemInfo(this, "Save", "?/?/form[@name='Microsoft Excel']/button[@name='Save']", "", 20000, null, "8ba43f6e-b2e3-48cd-a947-adf44316378c");
                _cancelInfo = new RepoItemInfo(this, "Cancel", "?/?/form[@name='Microsoft Excel']/button[@name='Cancel']", ".//button[@name='Cancel']", 30000, null, "643570b8-f5da-428a-96f4-3123ed030090");
                _cell7Info = new RepoItemInfo(this, "Cell7", ".//container[@automationid='desktop automation.xlsx']/?/?/table[@automationid='Grid']/cell[@name='7']", ".//cell[@name='7']", 30000, null, "35145290-7ff1-4919-a910-975b3030f722");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0adf07bc-1a4b-4842-ac4b-4e057a0517a5")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0adf07bc-1a4b-4842-ac4b-4e057a0517a5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BlankWorkbook item.
            /// </summary>
            [RepositoryItem("bd80e14e-40f5-46f5-9522-83bae726afe9")]
            public virtual Ranorex.ListItem BlankWorkbook
            {
                get
                {
                    return _blankworkbookInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The BlankWorkbook item info.
            /// </summary>
            [RepositoryItemInfo("bd80e14e-40f5-46f5-9522-83bae726afe9")]
            public virtual RepoItemInfo BlankWorkbookInfo
            {
                get
                {
                    return _blankworkbookInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("4e5af33e-e3f1-4949-9053-462492a94660")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("4e5af33e-e3f1-4949-9053-462492a94660")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The FileSave item.
            /// </summary>
            [RepositoryItem("da61aaed-aa63-40b4-ad20-30e6442f0a2d")]
            public virtual Ranorex.Button FileSave
            {
                get
                {
                    return _filesaveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The FileSave item info.
            /// </summary>
            [RepositoryItemInfo("da61aaed-aa63-40b4-ad20-30e6442f0a2d")]
            public virtual RepoItemInfo FileSaveInfo
            {
                get
                {
                    return _filesaveInfo;
                }
            }

            /// <summary>
            /// The DesktopAutomationTest item.
            /// </summary>
            [RepositoryItem("54f041f4-2a87-4bd8-8585-3e7d4e95725b")]
            public virtual Ranorex.ListItem DesktopAutomationTest
            {
                get
                {
                    return _desktopautomationtestInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The DesktopAutomationTest item info.
            /// </summary>
            [RepositoryItemInfo("54f041f4-2a87-4bd8-8585-3e7d4e95725b")]
            public virtual RepoItemInfo DesktopAutomationTestInfo
            {
                get
                {
                    return _desktopautomationtestInfo;
                }
            }

            /// <summary>
            /// The ButtonSave item.
            /// </summary>
            [RepositoryItem("6eea1926-b203-4e78-940a-fa9c5bced349")]
            public virtual Ranorex.Button ButtonSave
            {
                get
                {
                    return _buttonsaveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonSave item info.
            /// </summary>
            [RepositoryItemInfo("6eea1926-b203-4e78-940a-fa9c5bced349")]
            public virtual RepoItemInfo ButtonSaveInfo
            {
                get
                {
                    return _buttonsaveInfo;
                }
            }

            /// <summary>
            /// The CellE item.
            /// </summary>
            [RepositoryItem("d6ef9780-c0fa-4604-805e-0cbcdd4d30c4")]
            public virtual Ranorex.Cell CellE
            {
                get
                {
                    return _celleInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellE item info.
            /// </summary>
            [RepositoryItemInfo("d6ef9780-c0fa-4604-805e-0cbcdd4d30c4")]
            public virtual RepoItemInfo CellEInfo
            {
                get
                {
                    return _celleInfo;
                }
            }

            /// <summary>
            /// The Cell4 item.
            /// </summary>
            [RepositoryItem("8296625c-faae-4f8c-9fb7-1394afece428")]
            public virtual Ranorex.Cell Cell4
            {
                get
                {
                    return _cell4Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Cell4 item info.
            /// </summary>
            [RepositoryItemInfo("8296625c-faae-4f8c-9fb7-1394afece428")]
            public virtual RepoItemInfo Cell4Info
            {
                get
                {
                    return _cell4Info;
                }
            }

            /// <summary>
            /// The Insert item.
            /// </summary>
            [RepositoryItem("7e697a46-2f23-4edb-b004-9c978ace0347")]
            public virtual Ranorex.MenuItem Insert
            {
                get
                {
                    return _insertInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Insert item info.
            /// </summary>
            [RepositoryItemInfo("7e697a46-2f23-4edb-b004-9c978ace0347")]
            public virtual RepoItemInfo InsertInfo
            {
                get
                {
                    return _insertInfo;
                }
            }

            /// <summary>
            /// The CellF item.
            /// </summary>
            [RepositoryItem("269ffb61-d4a8-487a-b201-88120e341fe6")]
            public virtual Ranorex.Cell CellF
            {
                get
                {
                    return _cellfInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellF item info.
            /// </summary>
            [RepositoryItemInfo("269ffb61-d4a8-487a-b201-88120e341fe6")]
            public virtual RepoItemInfo CellFInfo
            {
                get
                {
                    return _cellfInfo;
                }
            }

            /// <summary>
            /// The Delete item.
            /// </summary>
            [RepositoryItem("fd815826-7012-4b8f-aded-cdcc7c9632a9")]
            public virtual Ranorex.MenuItem Delete
            {
                get
                {
                    return _deleteInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Delete item info.
            /// </summary>
            [RepositoryItemInfo("fd815826-7012-4b8f-aded-cdcc7c9632a9")]
            public virtual RepoItemInfo DeleteInfo
            {
                get
                {
                    return _deleteInfo;
                }
            }

            /// <summary>
            /// The StatusBar item.
            /// </summary>
            [RepositoryItem("b9a6dab5-636c-4f5b-a034-809a31680395")]
            public virtual Ranorex.StatusBar StatusBar
            {
                get
                {
                    return _statusbarInfo.CreateAdapter<Ranorex.StatusBar>(true);
                }
            }

            /// <summary>
            /// The StatusBar item info.
            /// </summary>
            [RepositoryItemInfo("b9a6dab5-636c-4f5b-a034-809a31680395")]
            public virtual RepoItemInfo StatusBarInfo
            {
                get
                {
                    return _statusbarInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("a87772c0-540f-4ef0-afbe-ae54fb2fc0af")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("a87772c0-540f-4ef0-afbe-ae54fb2fc0af")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The Save item.
            /// </summary>
            [RepositoryItem("8ba43f6e-b2e3-48cd-a947-adf44316378c")]
            public virtual Ranorex.Button Save
            {
                get
                {
                    return _saveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Save item info.
            /// </summary>
            [RepositoryItemInfo("8ba43f6e-b2e3-48cd-a947-adf44316378c")]
            public virtual RepoItemInfo SaveInfo
            {
                get
                {
                    return _saveInfo;
                }
            }

            /// <summary>
            /// The Cancel item.
            /// </summary>
            [RepositoryItem("643570b8-f5da-428a-96f4-3123ed030090")]
            public virtual Ranorex.Button Cancel
            {
                get
                {
                    return _cancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Cancel item info.
            /// </summary>
            [RepositoryItemInfo("643570b8-f5da-428a-96f4-3123ed030090")]
            public virtual RepoItemInfo CancelInfo
            {
                get
                {
                    return _cancelInfo;
                }
            }

            /// <summary>
            /// The Cell7 item.
            /// </summary>
            [RepositoryItem("35145290-7ff1-4919-a910-975b3030f722")]
            public virtual Ranorex.Cell Cell7
            {
                get
                {
                    return _cell7Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Cell7 item info.
            /// </summary>
            [RepositoryItemInfo("35145290-7ff1-4919-a910-975b3030f722")]
            public virtual RepoItemInfo Cell7Info
            {
                get
                {
                    return _cell7Info;
                }
            }

            /// <summary>
            /// The Sheet1 folder.
            /// </summary>
            [RepositoryFolder("d2d49dbe-67ca-486e-a0d8-1d28096599de")]
            public virtual Desktop_Automation_GotisRepositoryFolders.Sheet1Folder Sheet1
            {
                get { return _sheet1; }
            }
        }

        /// <summary>
        /// The Sheet1Folder folder.
        /// </summary>
        [RepositoryFolder("d2d49dbe-67ca-486e-a0d8-1d28096599de")]
        public partial class Sheet1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _cellc1Info;
            RepoItemInfo _celle1Info;
            RepoItemInfo _cella5Info;
            RepoItemInfo _celld5Info;
            RepoItemInfo _cella6Info;

            /// <summary>
            /// Creates a new Sheet1  folder.
            /// </summary>
            public Sheet1Folder(RepoGenBaseFolder parentFolder) :
                    base("Sheet1", ".//table[@name='Sheet1']", parentFolder, 30000, null, false, "d2d49dbe-67ca-486e-a0d8-1d28096599de", "")
            {
                _cellc1Info = new RepoItemInfo(this, "CellC1", "row[@index='1']/cell[@address='C1']", "", 30000, null, "d998b7f5-9372-4e5a-ac36-7e9d677ffbb5");
                _celle1Info = new RepoItemInfo(this, "CellE1", "row[@index='1']/cell[@address='E1']", "", 30000, null, "3083c0dd-d1e3-43c2-a753-aa2b17562905");
                _cella5Info = new RepoItemInfo(this, "CellA5", "row[@index='5']/cell[@address='A5']", "", 30000, null, "fe4e29ed-1113-4c94-8b21-693bbd99912f");
                _celld5Info = new RepoItemInfo(this, "CellD5", "row[@index='5']/cell[@address='D5']", "", 30000, null, "4538a3e1-f668-46c5-bc13-59313b6d3569");
                _cella6Info = new RepoItemInfo(this, "CellA6", "row[@index='6']/cell[@address='A6']", "", 30000, null, "0e0dccb0-9e49-42e4-a801-be85d6ff7fbe");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d2d49dbe-67ca-486e-a0d8-1d28096599de")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d2d49dbe-67ca-486e-a0d8-1d28096599de")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CellC1 item.
            /// </summary>
            [RepositoryItem("d998b7f5-9372-4e5a-ac36-7e9d677ffbb5")]
            public virtual Ranorex.Cell CellC1
            {
                get
                {
                    return _cellc1Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellC1 item info.
            /// </summary>
            [RepositoryItemInfo("d998b7f5-9372-4e5a-ac36-7e9d677ffbb5")]
            public virtual RepoItemInfo CellC1Info
            {
                get
                {
                    return _cellc1Info;
                }
            }

            /// <summary>
            /// The CellE1 item.
            /// </summary>
            [RepositoryItem("3083c0dd-d1e3-43c2-a753-aa2b17562905")]
            public virtual Ranorex.Cell CellE1
            {
                get
                {
                    return _celle1Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellE1 item info.
            /// </summary>
            [RepositoryItemInfo("3083c0dd-d1e3-43c2-a753-aa2b17562905")]
            public virtual RepoItemInfo CellE1Info
            {
                get
                {
                    return _celle1Info;
                }
            }

            /// <summary>
            /// The CellA5 item.
            /// </summary>
            [RepositoryItem("fe4e29ed-1113-4c94-8b21-693bbd99912f")]
            public virtual Ranorex.Cell CellA5
            {
                get
                {
                    return _cella5Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellA5 item info.
            /// </summary>
            [RepositoryItemInfo("fe4e29ed-1113-4c94-8b21-693bbd99912f")]
            public virtual RepoItemInfo CellA5Info
            {
                get
                {
                    return _cella5Info;
                }
            }

            /// <summary>
            /// The CellD5 item.
            /// </summary>
            [RepositoryItem("4538a3e1-f668-46c5-bc13-59313b6d3569")]
            public virtual Ranorex.Cell CellD5
            {
                get
                {
                    return _celld5Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellD5 item info.
            /// </summary>
            [RepositoryItemInfo("4538a3e1-f668-46c5-bc13-59313b6d3569")]
            public virtual RepoItemInfo CellD5Info
            {
                get
                {
                    return _celld5Info;
                }
            }

            /// <summary>
            /// The CellA6 item.
            /// </summary>
            [RepositoryItem("0e0dccb0-9e49-42e4-a801-be85d6ff7fbe")]
            public virtual Ranorex.Cell CellA6
            {
                get
                {
                    return _cella6Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellA6 item info.
            /// </summary>
            [RepositoryItemInfo("0e0dccb0-9e49-42e4-a801-be85d6ff7fbe")]
            public virtual RepoItemInfo CellA6Info
            {
                get
                {
                    return _cella6Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
