///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Desktop_Automation_Gotis
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("1ac3b718-4516-44d6-9e67-0801ef6c48df", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Desktop_Automation_GotisRepository repository.
        /// </summary>
        public static Desktop_Automation_GotisRepository repo = Desktop_Automation_GotisRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Book11Excel.BlankWorkbook' at 90;61.", repo.Book11Excel.BlankWorkbookInfo, new RecordItemIndex(0));
            repo.Book11Excel.BlankWorkbook.Click("90;61");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{F5}' with focus on 'Book11Excel'.", repo.Book11Excel.SelfInfo, new RecordItemIndex(1));
            repo.Book11Excel.Self.EnsureVisible();
            Keyboard.Press("{F5}");
            Delay.Milliseconds(19980);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'd1' with focus on 'Book11Excel'.", repo.Book11Excel.SelfInfo, new RecordItemIndex(2));
            repo.Book11Excel.Self.EnsureVisible();
            Keyboard.Press("d1");
            Delay.Milliseconds(9960);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Book11Excel.ButtonOK' at 19;12.", repo.Book11Excel.ButtonOKInfo, new RecordItemIndex(3));
            repo.Book11Excel.ButtonOK.Click("19;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '23{Down}66{Down}54{Down}78{Down}90{Down}=d1-d2{LShiftKey down}+{LShiftKey up}d3{LShiftKey down}+{LShiftKey up}d4{LShiftKey down}*{LShiftKey up}d5{Return}' with focus on 'Book11Excel'.", repo.Book11Excel.SelfInfo, new RecordItemIndex(4));
            repo.Book11Excel.Self.EnsureVisible();
            Keyboard.Press("23{Down}66{Down}54{Down}78{Down}90{Down}=d1-d2{LShiftKey down}+{LShiftKey up}d3{LShiftKey down}+{LShiftKey up}d4{LShiftKey down}*{LShiftKey up}d5{Return}", 30);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Book11Excel.FileSave' at 3;21.", repo.Book11Excel.FileSaveInfo, new RecordItemIndex(5));
            repo.Book11Excel.FileSave.Click("3;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Book11Excel.DesktopAutomationTest' at 332;36.", repo.Book11Excel.DesktopAutomationTestInfo, new RecordItemIndex(6));
            repo.Book11Excel.DesktopAutomationTest.Click("332;36");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'desktop automation' with focus on 'Book11Excel'.", repo.Book11Excel.SelfInfo, new RecordItemIndex(7));
            repo.Book11Excel.Self.EnsureVisible();
            Keyboard.Press("desktop automation");
            Delay.Milliseconds(19640);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Book11Excel.ButtonSave' at 50;18.", repo.Book11Excel.ButtonSaveInfo, new RecordItemIndex(8));
            repo.Book11Excel.ButtonSave.Click("50;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Book11Excel.Sheet1.CellE1' at 33;-11.", repo.Book11Excel.Sheet1.CellE1Info, new RecordItemIndex(9));
            repo.Book11Excel.Sheet1.CellE1.Click("33;-11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'Book11Excel.CellE' at 33;9.", repo.Book11Excel.CellEInfo, new RecordItemIndex(10));
            repo.Book11Excel.CellE.Click(System.Windows.Forms.MouseButtons.Right, "33;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Book11Excel.CellE' at 112;204.", repo.Book11Excel.CellEInfo, new RecordItemIndex(11));
            repo.Book11Excel.CellE.Click("112;204");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Book11Excel.Sheet1.CellA5' at -10;-8.", repo.Book11Excel.Sheet1.CellA5Info, new RecordItemIndex(12));
            repo.Book11Excel.Sheet1.CellA5.Click("-10;-8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'Book11Excel.Cell4' at 16;12.", repo.Book11Excel.Cell4Info, new RecordItemIndex(13));
            repo.Book11Excel.Cell4.Click(System.Windows.Forms.MouseButtons.Right, "16;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Book11Excel.Insert' at 78;10.", repo.Book11Excel.InsertInfo, new RecordItemIndex(14));
            repo.Book11Excel.Insert.Click("78;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Book11Excel.Sheet1.CellC1' at 232;-15.", repo.Book11Excel.Sheet1.CellC1Info, new RecordItemIndex(15));
            repo.Book11Excel.Sheet1.CellC1.Click("232;-15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'Book11Excel.CellF' at 40;5.", repo.Book11Excel.CellFInfo, new RecordItemIndex(16));
            repo.Book11Excel.CellF.Click(System.Windows.Forms.MouseButtons.Right, "40;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Book11Excel.Delete' at 53;14.", repo.Book11Excel.DeleteInfo, new RecordItemIndex(17));
            repo.Book11Excel.Delete.Click("53;14");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Book11Excel.Sheet1.CellA5' at -13;-8.", repo.Book11Excel.Sheet1.CellA5Info, new RecordItemIndex(18));
            //repo.Book11Excel.Sheet1.CellA5.Click("-13;-8");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'Book11Excel.Cell4' at 13;12.", repo.Book11Excel.Cell4Info, new RecordItemIndex(19));
            //repo.Book11Excel.Cell4.Click(System.Windows.Forms.MouseButtons.Right, "13;12");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Book11Excel.Cell7' at 104;230.", repo.Book11Excel.Cell7Info, new RecordItemIndex(20));
            repo.Book11Excel.Cell7.Click("104;230");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'Book11Excel.Cell7' at 13;11.", repo.Book11Excel.Cell7Info, new RecordItemIndex(21));
            repo.Book11Excel.Cell7.Click(System.Windows.Forms.MouseButtons.Right, "13;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Book11Excel.Delete' at 63;14.", repo.Book11Excel.DeleteInfo, new RecordItemIndex(22));
            repo.Book11Excel.Delete.Click("63;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Book11Excel.Sheet1.CellD5' at 58;12.", repo.Book11Excel.Sheet1.CellD5Info, new RecordItemIndex(23));
            repo.Book11Excel.Sheet1.CellD5.Click("58;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Book11Excel.Sheet1.CellD5' at 58;11.", repo.Book11Excel.Sheet1.CellD5Info, new RecordItemIndex(24));
            repo.Book11Excel.Sheet1.CellD5.MoveTo("58;11");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'Book11Excel.Sheet1.CellD5' at 55;-19.", repo.Book11Excel.Sheet1.CellD5Info, new RecordItemIndex(25));
            repo.Book11Excel.Sheet1.CellD5.MoveTo("55;-19");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Ckey}{LControlKey up}' with focus on 'Book11Excel'.", repo.Book11Excel.SelfInfo, new RecordItemIndex(26));
            repo.Book11Excel.Self.EnsureVisible();
            Keyboard.Press("{LControlKey down}{Ckey}{LControlKey up}", 20000);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Book11Excel.Sheet1.CellE1' at 34;7.", repo.Book11Excel.Sheet1.CellE1Info, new RecordItemIndex(27));
            repo.Book11Excel.Sheet1.CellE1.Click("34;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Vkey}{LControlKey up}' with focus on 'Book11Excel.Sheet1.CellE1'.", repo.Book11Excel.Sheet1.CellE1Info, new RecordItemIndex(28));
            repo.Book11Excel.Sheet1.CellE1.PressKeys("{LControlKey down}{Vkey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Book11Excel.StatusBar' at 382;-777.", repo.Book11Excel.StatusBarInfo, new RecordItemIndex(29));
            repo.Book11Excel.StatusBar.Click("382;-777");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Book11Excel.Close' at 22;18.", repo.Book11Excel.CloseInfo, new RecordItemIndex(30));
            repo.Book11Excel.Close.Click("22;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Book11Excel.Save' at 37;13.", repo.Book11Excel.SaveInfo, new RecordItemIndex(31));
            repo.Book11Excel.Save.Click("37;13");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
